'use strict';
// import collections from './collections';
// import granules from './granules';
import requests from './requests';
// import pdrs from './pdrs';
// import providers from './providers';
import forms from './forms';
import questions from './questions';
import users from './users';
import groups from './groups';
// import errors from './errors';
import roles from './roles';
import workflows from './workflows';
// import executions from './executions';
// import operations from './operations';
// import rules from './rules';
// import reconciliationReports from './reconciliation-reports';

const paths = [requests, forms, questions, users, groups, workflows, roles];
export default paths;
