// Authentication
export const LOGIN = 'LOGIN';
export const LOGIN_INFLIGHT = 'LOGIN_INFLIGHT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_TOKEN_INFLIGHT = 'FETCH_TOKEN_INFLIGHT';
export const FETCH_TOKEN_ERROR = 'FETCH_TOKEN_ERROR';
export const DELETE_TOKEN = 'DELETE_TOKEN';
export const SET_TOKEN = 'SET_TOKEN';
export const ADD_INSTANCE_META = 'ADD_INSTANCE_META';

// Stats
export const STATS = 'STATS';
export const STATS_INFLIGHT = 'STATS_INFLIGHT';
export const STATS_ERROR = 'STATS_ERROR';

// Count
export const COUNT = 'COUNT';
export const COUNT_INFLIGHT = 'COUNT_INFLIGHT';
export const COUNT_ERROR = 'COUNT_ERROR';
// Workflows
export const WORKFLOWS = 'WORKFLOWS';
export const WORKFLOW = 'WORKFLOW';
export const WORKFLOW_INFLIGHT = 'WORKFLOW_INFLIGHT';
export const WORKFLOW_ERROR = 'WORKFLOW_ERROR';

// Metrics
export const METRICS = 'METRICS';
export const METRICS_INFLIGHT = 'METRICS_INFLIGHT';
export const METRICS_ERROR = 'METRICS_ERROR';

// Roles
export const ROLE = 'ROLE';
export const ROLE_INFLIGHT = 'ROLE_INFLIGHT';
export const ROLE_ERROR = 'ROLE_ERROR';
export const ROLES = 'ROLES';
export const ROLES_INFLIGHT = 'ROLES_INFLIGHT';
export const ROLES_ERROR = 'ROLES_ERROR';

// Conversations
export const CONVERSATION = 'CONVERSATION';
export const CONVERSATION_INFLIGHT = 'CONVERSATION_INFLIGHT';
export const CONVERSATION_ERROR = 'CONVERSATION_ERROR';
export const CONVERSATIONS = 'CONVERSATIONS';
export const CONVERSATIONS_INFLIGHT = 'CONVERSATIONS_INFLIGHT';
export const CONVERSATIONS_ERROR = 'CONVERSATIONS_ERROR';
export const CONVERSATION_REPLY = 'CONVERSATION_REPLY';
export const CONVERSATION_REPLY_INFLIGHT = 'CONVERSATION_REPLY_INFLIGHT';
export const CONVERSATION_REPLY_ERROR = 'CONVERSATION_REPLY_ERROR';
export const CONVERSATION_ADD_USER = 'CONVERSATION_ADD_USER';
export const CONVERSATION_REMOVE_USER = 'CONVERSATION_REMOVE_USER';
export const CONVERSATION_ADD_USER_INFLIGHT = 'CONVERSATION_ADD_USERS_INFLIGHT';
export const CONVERSATION_ADD_USER_ERROR = 'CONVERSATION_ADD_USERS_ERROR';

export const SCHEMA = 'SCHEMA';
export const SCHEMA_INFLIGHT = 'SCHEMA_INFLIGHT';
export const SCHEMA_ERROR = 'SCHEMA_ERROR';

// API
export const API_VERSION = 'API_VERSION';
export const API_VERSION_ERROR = 'API_VERSION_ERROR';
export const API_VERSION_COMPATIBLE = 'API_VERSION_COMPATIBLE';
export const API_VERSION_INCOMPATIBLE = 'API_VERSION_INCOMPATIBLE';
export const CALL_API = 'CALL_API';

// Datepicker filtering
export const DATEPICKER_DROPDOWN_FILTER = 'DATEPICKER_DROPDOWN_FILTER';
export const DATEPICKER_DATECHANGE = 'DATEPICKER_DATECHANGE';
export const DATEPICKER_HOUR_FORMAT = 'DATEPICKER_HOUR_FORMAT';
// Upload
export const UPLOAD = 'UPLOAD';
export const UPLOAD_INFLIGHT = 'UPLOAD_INFLIGHT';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';
export const UPLOAD_STEP = 'UPLOAD_STEP';
export const UPLOAD_STEP_INFLIGHT = 'UPLOAD_STEP_INFLIGHT';
export const UPLOAD_STEP_ERROR = 'UPLOAD_STEP_ERROR';
// Requests
export const REQUEST = 'REQUEST';
export const REQUESTS = 'REQUESTS';
export const REQUEST_REVIEW = 'REQUEST_REVIEW';
export const REQUEST_REVIEW_INFLIGHT = 'REQUEST_REVIEW_INFLIGHT';
export const REQUEST_INFLIGHT = 'REQUEST_INFLIGHT';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUESTS_INFLIGHT = 'REQUESTS_INFLIGHT';
export const REQUESTS_ERROR = 'REQUESTS_ERROR';
export const REQUEST_APPLYWORKFLOW = 'REQUEST_APPLYWORKFLOW';
export const REQUEST_APPLYWORKFLOW_INFLIGHT = 'REQUEST_APPLYWORKFLOW_INFLIGHT';
export const REQUEST_APPLYWORKFLOW_ERROR = 'REQUEST_APPLYWORKFLOW_ERROR';
export const REQUEST_DELETE = 'REQUEST_DELETE';
export const REQUEST_DELETE_INFLIGHT = 'REQUEST_DELETE_INFLIGHT';
export const REQUEST_DELETE_ERROR = 'REQUEST_DELETE_ERROR';
export const REQUEST_WITHDRAW = 'REQUEST_WITHDRAW';
export const REQUEST_WITHDRAW_INFLIGHT = 'REQUEST_WITHDRAW_INFLIGHT';
export const REQUEST_WITHDRAW_ERROR = 'REQUEST_WITHDRAW_ERROR';
export const REQUEST_RESTORE = 'REQUEST_RESTORE';
export const REQUEST_RESTORE_INFLIGHT = 'REQUEST_RESTORE_INFLIGHT';
export const REQUEST_RESTORE_ERROR = 'REQUEST_RESTORE_ERROR';
export const REQUEST_ADDUSER = 'REQUEST_ADDUSER';
export const REQUEST_ADDUSER_INFLIGHT = 'REQUEST_ADDUSER_INFLIGHT';
export const REQUEST_ADDUSER_ERROR = 'REQUEST_ADDUSER_ERROR';
export const REQUEST_DELETEUSER = 'REQUEST_DELETEUSER';
export const REQUEST_DELETEUSER_INFLIGHT = 'REQUEST_DELETEUSER_INFLIGHT';
export const REQUEST_DELETEUSER_ERROR = 'REQUEST_DELETEUSER_ERROR';
export const REQUEST_REVIEWERS = 'REQUEST_REVIEWERS';
export const REQUEST_REVIEWERS_INFLIGHT = 'REQUEST_REVIEWERS_INFLIGHT';
export const REQUEST_REVIEWERS_ERROR = 'REQUEST_REVIEWERS_ERROR';

// Groups
export const GROUP = 'GROUP';
export const GROUP_INFLIGHT = 'GROUP_INFLIGHT';
export const GROUP_ERROR = 'GROUP_ERROR';
export const NEW_GROUP = 'NEW_GROUP';
export const NEW_GROUP_INFLIGHT = 'NEW_GROUP_INFLIGHT';
export const NEW_GROUP_ERROR = 'NEW_GROUP_ERROR';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const UPDATE_GROUP_INFLIGHT = 'UPDATE_GROUP_INFLIGHT';
export const UPDATE_GROUP_ERROR = 'UPDATE_GROUP_ERROR';
export const UPDATE_GROUP_CLEAR = 'UPDATE_GROUP_CLEAR';
export const GROUPS = 'GROUPS';
export const GROUPS_INFLIGHT = 'GROUPS_INFLIGHT';
export const GROUPS_ERROR = 'GROUPS_ERROR';

// Users
export const USER = 'USER';
export const USER_INFLIGHT = 'USER_INFLIGHT';
export const USER_ERROR = 'USER_ERROR';
export const USERS = 'USERS';
export const USERS_INFLIGHT = 'USERS_INFLIGHT';
export const USERS_ERROR = 'USERS_ERROR';
export const USER_ADDROLE = 'USER_ADDROLE';
export const USER_ADDROLE_INFLIGHT = 'USER_ADDROLE_INFLIGHT';
export const USER_REMOVEROLE = 'USER_REMOVEROLE';
export const USER_REMOVEROLE_INFLIGHT = 'USER_REMOVEROLE_INFLIGHT';
export const USER_ADDGROUP = 'USER_ADDGROUP';
export const USER_ADDGROUP_INFLIGHT = 'USER_ADDGROUP_INFLIGHT';
export const USER_REMOVEGROUP = 'USER_REMOVEGROUP';
export const USER_REMOVEGROUP_INFLIGHT = 'USER_REMOVEGROUP_INFLIGHT';
export const USER_CREATE = 'USER_CREATE';
export const USERNAME_UPDATE = 'USERNAME_UPDATE';

// Forms
export const FORM = 'FORM';
export const FORM_INFLIGHT = 'FORM_INFLIGHT';
export const FORM_ERROR = 'FORM_ERROR';
export const REVIEW = 'REVIEW';
export const REVIEW_INFLIGHT = 'REVIEW_INFLIGHT';
export const REVIEW_ERROR = 'REVIEW_ERROR';
export const FORMS = 'FORMS';
export const FORMS_INFLIGHT = 'FORMS_INFLIGHT';
export const FORMS_ERROR = 'FORMS_ERROR';

// Sections
export const SECTION = 'SECTION';

// Questions
export const QUESTION = 'QUESTION';
export const QUESTION_INFLIGHT = 'QUESTION_INFLIGHT';
export const QUESTIONS = 'QUESTIONS';
export const QUESTIONS_INFLIGHT = 'QUESTIONS_INFLIGHT';
export const QUESTIONS_ERROR = 'QUESTIONS_ERROR';

// Daacs
export const DAACS = 'DAACS';
export const DAACS_INFLIGHT = 'DAACS_INFLIGHT';
export const DAACS_ERROR = 'DAACS_ERROR';

// Inputs
export const INPUTS = 'INPUTS';

// Model
export const MODEL = 'MODEL';
export const MODEL_INFLIGHT = 'MODEL_INFLIGHT';

// Module
export const GET_MODULE_UI = 'GET_MODULE_UI';
export const GET_MODULE_UI_INFLIGHT = 'GET_MODULE_UI_INFLIGHT';
export const GET_MODULE_UI_ERROR = 'GET_MODULE_UI_ERROR';
export const LIST_MODULES = 'LIST_MODULES';
export const LIST_MODULES_INFLIGHT = 'LIST_MODULES_INFLIGHT';
export const LIST_MODULES_ERROR = 'LIST_MODULES_ERROR';

// SearchModal
export const SEARCH_MODAL = 'SEARCH_MODAL';
export const SEARCH_MODAL_INFLIGHT = 'SEARCH_MODAL_INFLIGHT';

// GetUploadUrl
export const GET_SIGNED_PUT = 'GET_SIGNED_PUT';

// Note
export const NOTE_ADD_VIEWER = 'NOTE_ADD_VIEWER';
export const NOTE_ADD_VIEWER_INFLIGHT = 'NOTE_ADD_VIEWER_INFLIGHT';
export const NOTE_ADD_VIEWER_ERROR = 'NOTE_ADD_VIEWER_ERROR';

export const NOTE_REMOVE_VIEWER = 'NOTE_REMOVE_VIEWER';
export const NOTE_REMOVE_VIEWER_INFLIGHT = 'NOTE_REMOVE_VIEWER_INFLIGHT';
export const NOTE_REMOVE_VIEWER_ERROR = 'NOTE_REMOVE_VIEWER_ERROR';

export const NOTE_ADD_VIEWER_ROLE = 'NOTE_ADD_VIEWER_ROLE';
export const NOTE_ADD_VIEWER_ROLE_INFLIGHT = 'NOTE_ADD_VIEWER_ROLE_INFLIGHT';
export const NOTE_ADD_VIEWER_ROLE_ERROR = 'NOTE_ADD_VIEWER_ROLE_ERROR';

export const NOTE_REMOVE_VIEWER_ROLE = 'NOTE_REMOVE_VIEWER_ROLE';
export const NOTE_REMOVE_VIEWER_ROLE_INFLIGHT = 'NOTE_REMOVE_VIEWER_ROLE_INFLIGHT';
export const NOTE_REMOVE_VIEWER_ROLE_ERROR = 'NOTE_REMOVE_VIEWER_ROLE_ERROR';

// Steps
export const STEP = 'STEP';
export const STEP_INFLIGHT = 'STEP_INFLIGHT';
export const STEP_ERROR = 'STEP_ERROR';
export const STEPS = 'STEPS';
export const STEPS_INFLIGHT = 'STEPS_INFLIGHT';
export const STEPS_ERROR = 'STEPS_ERROR';
